name: CI/CD

on:
  push:
    branches: ["main"] 
    paths: ["addons/sourcemod/scripting/**"]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download SM 1.11 6502
        run: wget -O sourcemod.tar.gz https://sm.alliedmods.net/smdrop/1.11/sourcemod-1.11.0-git6502-linux.tar.gz
      - name: Extract SourceMod
        run: tar -xzf sourcemod.tar.gz
      - name: Compile Lilac
        run: |
          ./addons/sourcemod/scripting/compile.sh lilac.sp
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: plugins
          path: | 
            addons/sourcemod/scripting/compiled/lilac.smx
          retention-days: 1
          
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download Lilac
        uses: actions/download-artifact@v4
        with:
          name: plugins
          path: addons/sourcemod/plugins
      - id: commit
        uses: EndBug/add-and-commit@v9
      - name: Compress Files
        run: |
          zip -r core-plugins.zip addons      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: core-plugins.zip
          generate_release_notes: true
          tag_name: ${{ steps.commit.outputs.commit_sha}}
          make_latest: "true"